import "./globals.css";
import Headers from "@/components/Headers";
import { ThemeProvider } from "@/components/ThemeProviders";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="overflow-x-clip">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Headers />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
